### PR TITLE
Hindu muppala greeting

### PR DESCRIPTION
**Pull request by hindu-muppala**
## Issue Details
##4
Please give review and suggestion

### How this might affect the overall project?

<br/>

## Check List (Check all the boxes which are applicable)
- [ ] My code follows the best practices mentioned in the [contribution guide] (link-to-contri-guide) .
- [ ] My change requires a change to the documentation.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### CODE REVIEW

**Comment by prakharporwal** [comment]
Hey @hindu-muppala ! Thanks for raising this PR.
I am trying the file on a separate repository the file seems to not work. 
Have you tried it out on some repo of yours ?
@siddhant-khisty is it working for you ?

**Comment by hindu-muppala** [comment]
@prakharporwal , I have problem with workflow for my account ,it is giving whether workflow is worked or not after 5days. So I asked for suggestion. I tried so some workflows, but none of them work. 
I will work on this issue soon.

**Comment by hindu-muppala** [comment]
@prakharporwal ,once review this pull request and please give review ,so that I can add necessary enhancement. I also tested this action,it is working perfectly.

**Comment by prakharporwal** [comment]
@hindu-muppala  Move the greeting.yml file inside `.github/workflows` directory
else I don't think it gets triggered.
Making these changes makes it work on my repo.

**Comment by prakharporwal** [comment]
LGTM.  Thank you @hindu-muppala for contributing to this issue 🥳   🎉

**Pull request merged**
